/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ShowIndexRouteImport } from './../routes/show/index'
import { Route as ShowStoryIdRouteImport } from './../routes/show/$storyId'

const ShowIndexRoute = ShowIndexRouteImport.update({
  id: '/show/',
  path: '/show/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowStoryIdRoute = ShowStoryIdRouteImport.update({
  id: '/show/$storyId',
  path: '/show/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/show/$storyId': typeof ShowStoryIdRoute
  '/show/': typeof ShowIndexRoute
}
export interface FileRoutesByTo {
  '/show/$storyId': typeof ShowStoryIdRoute
  '/show': typeof ShowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/show/$storyId': typeof ShowStoryIdRoute
  '/show/': typeof ShowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/show/$storyId' | '/show/'
  fileRoutesByTo: FileRoutesByTo
  to: '/show/$storyId' | '/show'
  id: '__root__' | '/show/$storyId' | '/show/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShowStoryIdRoute: typeof ShowStoryIdRoute
  ShowIndexRoute: typeof ShowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/show/': {
      id: '/show/'
      path: '/show'
      fullPath: '/show/'
      preLoaderRoute: typeof ShowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$storyId': {
      id: '/show/$storyId'
      path: '/show/$storyId'
      fullPath: '/show/$storyId'
      preLoaderRoute: typeof ShowStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ShowStoryIdRoute: ShowStoryIdRoute,
  ShowIndexRoute: ShowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.ts'
import type { startInstance } from '../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
