import { Application, Assets, Container, Sprite } from "pixi.js";
import type { FederatedPointerEvent, Texture } from "pixi.js";
import { GlowFilter } from "pixi-filters/glow";
import type { Room } from "livekit-client";
import { saveSceneCastPosition } from "@/lib/scenes.fns";
import type { PropType } from "@/db/schema";
import type { PropMoveMessage } from "@/lib/livekit-messages";

export interface PixiCharacterProps {
  sceneCastId: string;
  castId: string;
  src: string;
  userId: string;
  type: PropType;
  initialX?: number;
  initialY?: number;
  initialRotation?: number;
  initialScaleX?: number;
  room?: Room | null;
  canDrag: boolean;
  stageWidth?: number;
  stageHeight?: number;
  app: Application;
  onReady?: () => void;
  onPositionChange?: (
    x: number,
    bounds: { minX: number; maxX: number },
  ) => void;
  onAnimationComplete?: () => void;
  backgroundRepeat?: boolean;
}

export type { PropMoveMessage };

const encoder = new TextEncoder();

function getAngle(a: { x: number; y: number }, b: { x: number; y: number }) {
  return Math.atan2(b.y - a.y, b.x - a.x) * (180 / Math.PI);
}

function getMidpoint(a: { x: number; y: number }, b: { x: number; y: number }) {
  return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 };
}

export class PixiCharacter {
  readonly container: Container;
  private sprite: Sprite;
  private glowFilter: GlowFilter;
  private readonly props: PixiCharacterProps;

  private isDragging = false;
  private dragOffset = { x: 0, y: 0 };
  private activePointers = new Map<number, { x: number; y: number }>();
  private lastSendTime = 0;
  private isSpeaking = false;

  // Double-tap detection
  private lastTapTime = 0;
  // Suppress spurious taps fired when fingers lift after a multi-touch gesture
  private suppressNextNTaps = 0;

  private onKeyDown: ((e: KeyboardEvent) => void) | null = null;

  constructor(props: PixiCharacterProps) {
    this.props = props;

    this.container = new Container();
    this.container.label = props.sceneCastId;
    this.container.zIndex = 1;
    this.container.x = props.initialX ?? 100;
    this.container.y = props.initialY ?? 100;

    this.glowFilter = new GlowFilter({
      color: 0xa855f7,
      outerStrength: 4,
      innerStrength: 0,
      distance: 15,
      quality: 0.5,
    });
    this.glowFilter.enabled = false;

    this.sprite = new Sprite();
    this.sprite.anchor.set(0.5);
    this.sprite.filters = [this.glowFilter];

    this.container.addChild(this.sprite);

    this.loadTexture();
  }

  private async loadTexture() {
    const { src, initialRotation = 0, initialScaleX = 1, app } = this.props;
    let texture: Texture;
    try {
      texture = await Assets.load(src);
    } catch {
      this.props.onReady?.();
      return;
    }

    // Guard: destroy() may have been called while the asset was loading
    if (this.sprite.destroyed) return;

    this.sprite.texture = texture;
    this.sprite.anchor.set(0.5);
    this.sprite.scale.x = initialScaleX;
    this.container.rotation = initialRotation * (Math.PI / 180);

    this.container.zIndex = 1;

    this.drawGlow();
    this.setupInteraction();
    this.props.onReady?.();

    // Trigger re-sort after zIndex assignment
    if (app.stage.sortableChildren) app.stage.sortChildren();
  }

  private drawGlow() {
    this.glowFilter.enabled = this.isSpeaking;
  }

  private setupInteraction() {
    const { canDrag } = this.props;

    this.sprite.eventMode = canDrag ? "static" : "none";
    this.sprite.cursor = canDrag ? "pointer" : "default";

    if (!canDrag) return;

    this.sprite.on("pointerdown", this.onPointerDown.bind(this));
    this.sprite.on("pointerup", this.onPointerUp.bind(this));
    this.sprite.on("pointerupoutside", this.onPointerUp.bind(this));
    this.sprite.on("globalpointermove", this.onStagePointerMove.bind(this));

    this.onKeyDown = (e: KeyboardEvent) => {
      if (e.code === "Space" && this.activePointers.size > 0)
        this.handleHorizontalFlip();
    };
    window.addEventListener("keydown", this.onKeyDown);
    this.sprite.on("tap", () => {
      // Eat taps generated by fingers lifting after a multi-touch gesture
      if (this.suppressNextNTaps > 0) {
        this.suppressNextNTaps--;
        this.lastTapTime = 0;
        return;
      }
      const now = Date.now();
      if (now - this.lastTapTime < 300) this.handleHorizontalFlip();
      this.lastTapTime = now;
    });
  }

  private onPointerDown(e: FederatedPointerEvent) {
    this.activePointers.set(e.pointerId, { x: e.clientX, y: e.clientY });

    if (this.activePointers.size === 1) {
      // Single finger — start drag
      this.isDragging = true;
      this.dragOffset = {
        x: this.container.x - e.global.x,
        y: this.container.y - e.global.y,
      };
      this.bringToTop();
    } else {
      // Multi-finger — stop drag, start gesture
      this.isDragging = false;
    }
  }

  private onPointerUp(e: FederatedPointerEvent) {
    const prevSize = this.activePointers.size;
    this.activePointers.delete(e.pointerId);

    // Transitioning out of multi-touch: suppress the tap events that PixiJS
    // fires after each pointerup, otherwise they register as a double-tap
    // and incorrectly flip the character's scaleX.
    if (prevSize >= 2 && this.activePointers.size < 2) {
      this.suppressNextNTaps = prevSize;
    }

    if (this.activePointers.size === 0) {
      this.isDragging = false;
      this.persistPosition();
    }
  }

  private onStagePointerMove(e: FederatedPointerEvent) {
    if (!this.props.canDrag) return;
    if (!this.activePointers.has(e.pointerId)) return;

    // Snapshot full previous state BEFORE updating the moved pointer so both
    // oldAngle and oldMid are computed from a consistent pre-event baseline.
    const prevStateMap = new Map(this.activePointers);
    this.activePointers.set(e.pointerId, { x: e.clientX, y: e.clientY });

    if (this.activePointers.size === 2) {
      // Two-finger: rotate + pan
      const currPointers = Array.from(this.activePointers.values());
      const prevPointers = Array.from(prevStateMap.values());

      // Need both previous positions; skip on the very first two-finger event
      if (prevPointers.length < 2) return;

      const newAngle = getAngle(currPointers[0], currPointers[1]);
      const newMid = getMidpoint(currPointers[0], currPointers[1]);
      const oldAngle = getAngle(prevPointers[0], prevPointers[1]);
      const oldMid = getMidpoint(prevPointers[0], prevPointers[1]);

      // Normalize to [-180, 180] to prevent wrap-around flip at the ±180° boundary
      let angleDelta = newAngle - oldAngle;
      if (angleDelta > 180) angleDelta -= 360;
      if (angleDelta < -180) angleDelta += 360;
      this.container.rotation += angleDelta * (Math.PI / 180);

      this.container.x += newMid.x - oldMid.x;
      this.container.y += newMid.y - oldMid.y;

      this.publishMove();
    } else if (this.isDragging && this.activePointers.size <= 1) {
      // Single finger drag
      const rawX = e.global.x + this.dragOffset.x;
      const rawY = e.global.y + this.dragOffset.y;
      this.container.x = this.clampX(rawX);
      this.container.y = this.clampY(rawY);
      this.publishMove();
    }
  }

  private clampX(x: number): number {
    const { stageWidth = 1280 } = this.props;
    return Math.min(Math.max(x, 0), stageWidth);
  }

  private clampY(y: number): number {
    const { stageHeight = 720 } = this.props;
    return Math.min(Math.max(y, 0), stageHeight);
  }

  private handleHorizontalFlip() {
    if (!this.props.canDrag) return;
    this.sprite.scale.x *= -1;
    this.drawGlow(); // redraw glow as width sign changed
    this.publishMove(true);
    this.persistPosition();
  }

  private publishMove(immediate = false) {
    const { room, canDrag, castId } = this.props;
    if (!room || !canDrag) return;
    const now = Date.now();
    if (!immediate && now - this.lastSendTime < 30) return;
    this.lastSendTime = now;

    const msg: PropMoveMessage = {
      type: "prop:move",
      castId,
      x: this.container.x,
      y: this.container.y,
      rotation: this.container.rotation * (180 / Math.PI),
      scaleX: this.sprite.scale.x,
      indexZ: 0,
    };
    this.props.room?.localParticipant.publishData(
      encoder.encode(JSON.stringify(msg)),
      { reliable: false },
    );
  }

  private persistPosition() {
    if (!this.props.canDrag) return;
    saveSceneCastPosition({
      data: {
        sceneCastId: this.props.sceneCastId,
        x: this.container.x,
        y: this.container.y,
        rotation: this.container.rotation * (180 / Math.PI),
        scaleX: this.sprite.scale.x,
      },
    });
  }

  private bringToTop() {
    const stage = this.props.app.stage;
    this.container.zIndex = stage.children.length + 1;
    stage.sortChildren();
  }

  updateSpeaking(isSpeaking: boolean) {
    if (this.isSpeaking === isSpeaking) return;
    this.isSpeaking = isSpeaking;
    this.drawGlow();
  }

  applyRemoteMove(msg: PropMoveMessage) {
    this.container.x = msg.x;
    this.container.y = msg.y;
    this.container.rotation = msg.rotation * (Math.PI / 180);
    this.sprite.scale.x = msg.scaleX;
  }

  saveCurrentPosition() {
    if (!this.props.canDrag) return;
    this.persistPosition();
  }

  destroy() {
    if (this.onKeyDown) window.removeEventListener("keydown", this.onKeyDown);
    this.container.destroy({ children: true });
  }
}
