/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StageRouteImport } from './routes/stage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppStoriesIndexRouteImport } from './routes/_app/stories/index'
import { Route as AppStoriesStoryIdIndexRouteImport } from './routes/_app/stories/$storyId/index'
import { Route as AppStoriesStoryIdScenesSceneIdRouteImport } from './routes/_app/stories/$storyId/scenes/$sceneId'

const StageRoute = StageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppStoriesIndexRoute = AppStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoriesStoryIdIndexRoute = AppStoriesStoryIdIndexRouteImport.update({
  id: '/stories/$storyId/',
  path: '/stories/$storyId/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoriesStoryIdScenesSceneIdRoute =
  AppStoriesStoryIdScenesSceneIdRouteImport.update({
    id: '/stories/$storyId/scenes/$sceneId',
    path: '/stories/$storyId/scenes/$sceneId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/stage': typeof StageRoute
  '/profile': typeof AppProfileRoute
  '/stories/': typeof AppStoriesIndexRoute
  '/stories/$storyId/': typeof AppStoriesStoryIdIndexRoute
  '/stories/$storyId/scenes/$sceneId': typeof AppStoriesStoryIdScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/stage': typeof StageRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/stories': typeof AppStoriesIndexRoute
  '/stories/$storyId': typeof AppStoriesStoryIdIndexRoute
  '/stories/$storyId/scenes/$sceneId': typeof AppStoriesStoryIdScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/stage': typeof StageRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/stories/': typeof AppStoriesIndexRoute
  '/_app/stories/$storyId/': typeof AppStoriesStoryIdIndexRoute
  '/_app/stories/$storyId/scenes/$sceneId': typeof AppStoriesStoryIdScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/stage'
    | '/profile'
    | '/stories/'
    | '/stories/$storyId/'
    | '/stories/$storyId/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/stage'
    | '/profile'
    | '/'
    | '/stories'
    | '/stories/$storyId'
    | '/stories/$storyId/scenes/$sceneId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/stage'
    | '/_app/profile'
    | '/_app/'
    | '/_app/stories/'
    | '/_app/stories/$storyId/'
    | '/_app/stories/$storyId/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  StageRoute: typeof StageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stage': {
      id: '/stage'
      path: '/stage'
      fullPath: '/stage'
      preLoaderRoute: typeof StageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stories/': {
      id: '/_app/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof AppStoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stories/$storyId/': {
      id: '/_app/stories/$storyId/'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId/'
      preLoaderRoute: typeof AppStoriesStoryIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stories/$storyId/scenes/$sceneId': {
      id: '/_app/stories/$storyId/scenes/$sceneId'
      path: '/stories/$storyId/scenes/$sceneId'
      fullPath: '/stories/$storyId/scenes/$sceneId'
      preLoaderRoute: typeof AppStoriesStoryIdScenesSceneIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStoriesIndexRoute: typeof AppStoriesIndexRoute
  AppStoriesStoryIdIndexRoute: typeof AppStoriesStoryIdIndexRoute
  AppStoriesStoryIdScenesSceneIdRoute: typeof AppStoriesStoryIdScenesSceneIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppStoriesIndexRoute: AppStoriesIndexRoute,
  AppStoriesStoryIdIndexRoute: AppStoriesStoryIdIndexRoute,
  AppStoriesStoryIdScenesSceneIdRoute: AppStoriesStoryIdScenesSceneIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  StageRoute: StageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
